[package]
name = "cool_utils"
version = "0.1.29"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.1"
nalgebra = "0.33.2"
